services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d

  postgres:
    image: postgres:16-alpine
    env_file: .env

  app:
    image: diegopeluffo_web
    build: .
    volumes:
      - .:/app
    env_file: .env
    restart: on-failure
    command: sh ./scripts/dev.sh
