services:
  nginx:
    extends:
      file: base.yml
      service: nginx
    depends_on:
      - app
    ports:
      - "5004:5004"

  postgres:
    extends:
      file: base.yml
      service: postgres
    ports:
      - "5432:5432"

  app:
    extends:
      file: base.yml
      service: app
    environment:
      - DJANGO_SETTINGS_MODULE=diegopeluffo_app.settings.settings_dev
    command: sh ./scripts/dev.sh
    build:
      args:
        - DJANGO_ENV=requirements_dev
    depends_on:
      - postgres
    ports:
      - "8004:8004"
