# Generated by Django 4.2.16 on 2025-06-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True, verbose_name='Project Title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Project Description')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Project URL')),
                ('kind_of_project', models.PositiveSmallIntegerField(choices=[(1, 'Current'), (2, 'Past')], default=200, verbose_name='Kind of Project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
