# Generated by Django 4.2.16 on 2025-06-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prolaborations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=400, null=True, verbose_name='Collaboration Title')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Collaboration URL')),
            ],
            options={
                'verbose_name': 'Collaboration',
                'verbose_name_plural': 'Collaborations',
            },
        ),
        migrations.CreateModel(
            name='ThesisAdvisory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=400, null=True, verbose_name='Thesis Title')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Thesis URL')),
            ],
            options={
                'verbose_name': 'Collaboration',
                'verbose_name_plural': 'Collaborations',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Project Title'),
        ),
    ]
