# Generated by Django 4.2.16 on 2025-06-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prolaborations', '0002_collaborations_thesisadvisory_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisadvisory',
            name='kind_of_thesis',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PhD'), (2, 'Master'), (3, 'Undergraduate')], default=200, verbose_name='Kind of Project'),
        ),
    ]
