# Generated by Django 4.2.16 on 2025-06-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prolaborations', '0003_thesisadvisory_kind_of_thesis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thesisadvisory',
            options={'verbose_name': 'Thesis', 'verbose_name_plural': 'Theses'},
        ),
        migrations.AddField(
            model_name='thesisadvisory',
            name='authors',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='thesisadvisory',
            name='kind_of_thesis',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PhD'), (2, 'Master'), (3, 'Undergraduate')], default=200, verbose_name='Kind of Thesis'),
        ),
    ]
