# Generated by Django 4.2.16 on 2025-06-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prolaborations', '0004_alter_thesisadvisory_options_thesisadvisory_authors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=400, null=True, verbose_name='Course Title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Course Description')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Course URL')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
