# Generated by Django 4.2.16 on 2025-06-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('publishing', models.TextField(blank=True, max_length=100, null=True, verbose_name='Publishing')),
                ('authors', models.TextField(blank=True, max_length=100, null=True, verbose_name='Authors')),
                ('isbn', models.TextField(blank=True, max_length=100, null=True, verbose_name='ISBN')),
                ('category', models.TextField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('book_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Book URL')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Boobks',
            },
        ),
        migrations.CreateModel(
            name='JournalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bibbase_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='BibBase URL')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
            },
        ),
        migrations.CreateModel(
            name='ThesesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('author', models.TextField(blank=True, max_length=100, null=True, verbose_name='Authors')),
                ('theses_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Book URL')),
                ('category', models.TextField(blank=True, max_length=100, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Theses',
                'verbose_name_plural': 'Theses',
            },
        ),
    ]
