# Generated by Django 4.2.16 on 2025-06-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='title',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='thesesinfo',
            name='title',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
