# Generated by Django 4.2.16 on 2025-05-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Personal Website')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('profile', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Professional Profile')),
                ('city', models.TextField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('researchgate_url', models.URLField(blank=True, null=True, verbose_name='ResearchGate URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
            ],
            options={
                'verbose_name': 'Personal Info',
                'verbose_name_plural': 'Infos',
            },
        ),
    ]
