# Generated by Django 4.2.16 on 2025-06-04 01:30

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0002_personalinfo_phone_personalinfo_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile',
            field=django_summernote.fields.SummernoteTextField(blank=True, max_length=3000, null=True, verbose_name='Professional Profile'),
        ),
    ]
