# Generated by Django 4.2.16 on 2025-06-04 01:53

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0003_alter_personalinfo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile',
            field=django_summernote.fields.SummernoteTextField(blank=True, max_length=5000, null=True, verbose_name='Professional Profile'),
        ),
    ]
