# Generated by Django 4.2.16 on 2025-06-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0005_alter_personalinfo_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True, verbose_name='Link Title')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Link URL')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='ResearchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True, verbose_name='Research Title')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Research Title')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Research URL')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Researches',
            },
        ),
    ]
