# Generated by Django 4.2.16 on 2025-06-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0006_linkinterest_researchline'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True, verbose_name='Link Title')),
                ('document', models.FileField(upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Download Document',
                'verbose_name_plural': 'Download Documents',
            },
        ),
        migrations.AddField(
            model_name='linkinterest',
            name='kind_of_link',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Link of Interest'), (2, 'Profile'), (3, 'My Stuff')], default=200, verbose_name='Kind of Link'),
        ),
        migrations.AlterField(
            model_name='researchline',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Research Description'),
        ),
    ]
