# Generated by Django 4.2.16 on 2025-06-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalinfo', '0008_researchline_kind_of_reseach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchline',
            old_name='kind_of_reseach',
            new_name='kind_of_research',
        ),
    ]
